### ISSUE TITLE
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist

### ISSUE THREAD

**Issue by nemosmithasf** [x86dev/docker-ttrss#40]
I'm trying to install the image on a Synology NAS via Docker.

I think my configurations are correct
**docker-ttrss**
![Screen Shot 2020-04-23 at 9 42 48 AM](https://user-images.githubusercontent.com/14184529/80105811-103fa480-8547-11ea-8721-4850e7c60e36.png)
![Screen Shot 2020-04-23 at 9 42 58 AM](https://user-images.githubusercontent.com/14184529/80105826-146bc200-8547-11ea-9732-648f8bb28ffd.png)

**postgres**
![Screen Shot 2020-04-23 at 9 43 10 AM](https://user-images.githubusercontent.com/14184529/80105853-1df52a00-8547-11ea-9173-fb88777c9caa.png)

But I get the following error / log when I run everything
```
date | stream | content
-- | -- | --
2020-04-23 13:32:52 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:52 | stdout | #2 {main}
2020-04-23 13:32:52 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:52 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:52 | stdout | Stack trace:
2020-04-23 13:32:52 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:52 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:52 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:52 | stdout | [13:32:52/393] Spawn interval: 120 sec
2020-04-23 13:32:51 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:51 | stdout | #2 {main}
2020-04-23 13:32:51 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:51 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:51 | stdout | Stack trace:
2020-04-23 13:32:51 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:51 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:51 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:51 | stdout | [13:32:51/389] Spawn interval: 120 sec
2020-04-23 13:32:50 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:50 | stdout | #2 {main}
2020-04-23 13:32:50 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:50 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:50 | stdout | Stack trace:
2020-04-23 13:32:50 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:50 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:50 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:50 | stdout | [13:32:50/385] Spawn interval: 120 sec
2020-04-23 13:32:49 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:49 | stdout | #2 {main}
2020-04-23 13:32:49 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:49 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:49 | stdout | Stack trace:
2020-04-23 13:32:49 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:49 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:49 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:49 | stdout | [13:32:49/381] Spawn interval: 120 sec
2020-04-23 13:32:48 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:48 | stdout | #2 {main}
2020-04-23 13:32:48 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:48 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:48 | stdout | Stack trace:
2020-04-23 13:32:48 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:48 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:48 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:48 | stdout | [13:32:48/377] Spawn interval: 120 sec
2020-04-23 13:32:47 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:47 | stdout | #2 {main}
2020-04-23 13:32:47 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:47 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:47 | stdout | Stack trace:
2020-04-23 13:32:47 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:47 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:47 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:47 | stdout | [13:32:47/373] Spawn interval: 120 sec
2020-04-23 13:32:46 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:46 | stdout | #2 {main}
2020-04-23 13:32:46 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:46 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:46 | stdout | Stack trace:
2020-04-23 13:32:46 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:46 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:46 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:46 | stdout | [13:32:46/369] Spawn interval: 120 sec
2020-04-23 13:32:45 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:45 | stdout | #2 {main}
2020-04-23 13:32:45 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:45 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:45 | stdout | Stack trace:
2020-04-23 13:32:45 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:45 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:45 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:45 | stdout | [13:32:45/365] Spawn interval: 120 sec
2020-04-23 13:32:45 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:45 | stdout | #2 {main}
2020-04-23 13:32:45 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:45 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:45 | stdout | Stack trace:
2020-04-23 13:32:45 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:45 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:45 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:45 | stdout | [13:32:45/361] Spawn interval: 120 sec
2020-04-23 13:32:44 | stdout | thrown in /var/www/ttrss/include/functions.php on line 864
2020-04-23 13:32:44 | stdout | #2 {main}
2020-04-23 13:32:44 | stdout | #1 /var/www/ttrss/update_daemon2.php(201): get_schema_version()
2020-04-23 13:32:44 | stdout | #0 /var/www/ttrss/include/functions.php(864): PDO->query('SELECT schema_v...')
2020-04-23 13:32:44 | stdout | Stack trace:
2020-04-23 13:32:44 | stdout | ^ in /var/www/ttrss/include/functions.php:864
2020-04-23 13:32:44 | stdout | LINE 1: SELECT schema_version FROM ttrss_version
2020-04-23 13:32:44 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ttrss_version" does not exist
2020-04-23 13:32:43 | stdout | [13:32:43/338] Spawn interval: 120 sec
2020-04-23 13:32:43 | stdout | [23-Apr-2020 13:32:43] NOTICE: ready to handle connections
2020-04-23 13:32:43 | stdout | [23-Apr-2020 13:32:43] NOTICE: fpm is running, pid 342
2020-04-23 13:32:42 | stdout | nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:39
2020-04-23 13:32:42 | stdout | [services.d] done.
2020-04-23 13:32:41 | stdout | [services.d] starting services
2020-04-23 13:32:41 | stdout | [cont-init.d] done.
2020-04-23 13:32:40 | stdout | [cont-init.d] 99-ttrss: exited 0.
2020-04-23 13:32:39 | stdout | Setup: Done
2020-04-23 13:32:39 | stdout | Update: Done
2020-04-23 13:32:39 | stdout | Updating: Updating permissions done
2020-04-23 13:32:38 | stdout | Updating: Updating permissions
2020-04-23 13:32:38 | stdout | Already up to date.
2020-04-23 13:32:38 | stdout | * branch            HEAD       -> FETCH_HEAD
2020-04-23 13:32:37 | stdout | From https://github.com/Gravemind/tt-rss-feedlish-theme
2020-04-23 13:32:36 | stdout | /srv/update-ttrss.sh: cd: line 37: can't cd to /var/www/ttrss/themes.local/levito-feedly-git: No such file or directory
2020-04-23 13:32:36 | stdout | Updating: Themes
2020-04-23 13:32:36 | stdout | fatal: unable to access 'https://github.com/feediron/ttrss_plugin-feediron.git/': The requested URL returned error: 504
2020-04-23 13:32:01 | stdout | Updating: FeedIron
2020-04-23 13:32:01 | stdout | Already up to date.
2020-04-23 13:32:01 | stdout | * branch            HEAD       -> FETCH_HEAD
2020-04-23 13:32:00 | stdout | From https://github.com/sepich/tt-rss-mobilize
2020-04-23 13:32:00 | stdout | Updating: Mobilize plugin
2020-04-23 13:32:00 | stdout | Already up to date.
2020-04-23 13:32:00 | stdout | * branch            HEAD       -> FETCH_HEAD
2020-04-23 13:32:00 | stdout | From https://git.tt-rss.org/git/tt-rss
2020-04-23 13:31:58 | stdout | Updating: Tiny Tiny RSS
2020-04-23 13:31:58 | stdout | Setup: Applying updates ...
2020-04-23 13:31:54 | stdout | pgsql:host=172.17.0.3;port=5432;dbname=ttrss;user=ttrss;password=ttrss;Database table for mobilize plugin not found, applying schema...
2020-04-23 13:31:53 | stdout | thrown in /srv/ttrss-configure-db.php on line 82
2020-04-23 13:31:53 | stdout | #1 {main}
2020-04-23 13:31:53 | stdout | #0 /srv/ttrss-configure-db.php(82): PDO->exec('')
2020-04-23 13:31:53 | stdout | Stack trace:
2020-04-23 13:31:53 | stdout | PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: trying to execute an empty query in /srv/ttrss-configure-db.php:82
2020-04-23 13:31:53 | stdout | PHP Warning:  file_get_contents(schema/ttrss_schema_pgsql.sql): failed to open stream: No such file or directory in /srv/ttrss-configure-db.php on line 77
2020-04-23 13:31:53 | stdout | PHP Notice:  Undefined variable: confpath in /srv/ttrss-configure-db.php on line 77
2020-04-23 13:31:53 | stdout | pgsql:host=172.17.0.3;port=5432;dbname=ttrss;user=ttrss;password=ttrss;pgsql:host=172.17.0.3;port=5432;dbname=ttrss;user=ttrss;password=ttrss;Database table not found, applying schema...
2020-04-23 13:31:52 | stdout | Configuring database for: config.php
2020-04-23 13:31:52 | stdout | PHP Notice:  Undefined variable: confpath in /srv/ttrss-configure-db.php on line 8
2020-04-23 13:31:50 | stdout | Setup: Database
2020-04-23 13:31:50 | stdout | Setup: Additional plugins:
2020-04-23 13:31:50 | stdout | Setup: URL is: http://localhost/
2020-04-23 13:31:50 | stdout | Unpacking objects: 100% (16/16) Unpacking objects: 100% (16/16), done.
2020-04-23 13:31:50 | stdout | Unpacking objects:   6% (1/16) Unpacking objects:  12% (2/16) Unpacking objects:  18% (3/16) Unpacking objects:  25% (4/16) Unpacking objects:  31% (5/16) Unpacking objects:  37% (6/16) Unpacking objects:  43% (7/16) Unpacking objects:  50% (8/16) Unpacking objects:  56% (9/16) Unpacking objects:  62% (10/16) Unpacking objects:  68% (11/16) Unpacking objects:  75% (12/16) Unpacking objects:  81% (13/16) Unpacking objects:  87% (14/16) Unpacking objects:  93% (15/16) remote: Total 16 (delta 1), reused 9 (delta 0), pack-reused 0[K
2020-04-23 13:31:50 | stdout | remote: Compressing objects:   6% (1/15)[K remote: Compressing objects:  13% (2/15)[K remote: Compressing objects:  20% (3/15)[K remote: Compressing objects:  26% (4/15)[K remote: Compressing objects:  33% (5/15)[K remote: Compressing objects:  40% (6/15)[K remote: Compressing objects:  46% (7/15)[K remote: Compressing objects:  53% (8/15)[K remote: Compressing objects:  60% (9/15)[K remote: Compressing objects:  66% (10/15)[K remote: Compressing objects:  73% (11/15)[K remote: Compressing objects:  80% (12/15)[K remote: Compressing objects:  86% (13/15)[K remote: Compressing objects:  93% (14/15)[K remote: Compressing objects: 100% (15/15)[K remote: Compressing objects: 100% (15/15), done.[K
2020-04-23 13:31:50 | stdout | remote: Counting objects:   6% (1/16)[K remote: Counting objects:  12% (2/16)[K remote: Counting objects:  18% (3/16)[K remote: Counting objects:  25% (4/16)[K remote: Counting objects:  31% (5/16)[K remote: Counting objects:  37% (6/16)[K remote: Counting objects:  43% (7/16)[K remote: Counting objects:  50% (8/16)[K remote: Counting objects:  56% (9/16)[K remote: Counting objects:  62% (10/16)[K remote: Counting objects:  68% (11/16)[K remote: Counting objects:  75% (12/16)[K remote: Counting objects:  81% (13/16)[K remote: Counting objects:  87% (14/16)[K remote: Counting objects:  93% (15/16)[K remote: Counting objects: 100% (16/16)[K remote: Counting objects: 100% (16/16), done.[K
2020-04-23 13:31:50 | stdout | remote: Enumerating objects: 16, done.[K
2020-04-23 13:31:49 | stdout | Cloning into '/var/www/ttrss/themes.local/gravemind-feedly-git'...
2020-04-23 13:31:49 | stdout | fatal: unable to access 'https://github.com/levito/tt-rss-feedly-theme.git/': The requested URL returned error: 504
2020-04-23 13:31:17 | stdout | Cloning into '/var/www/ttrss/themes.local/levito-feedly-git'...
2020-04-23 13:31:17 | stdout | Unpacking objects:  51% (23/45) Unpacking objects:  53% (24/45) Unpacking objects:  55% (25/45) Unpacking objects:  57% (26/45) Unpacking objects:  60% (27/45) Unpacking objects:  62% (28/45) Unpacking objects:  64% (29/45) Unpacking objects:  66% (30/45) Unpacking objects:  68% (31/45) Unpacking objects:  71% (32/45) Unpacking objects:  73% (33/45) Unpacking objects:  75% (34/45) Unpacking objects:  77% (35/45) Unpacking objects:  80% (36/45) Unpacking objects:  82% (37/45) Unpacking objects:  84% (38/45) Unpacking objects:  86% (39/45) Unpacking objects:  88% (40/45) Unpacking objects:  91% (41/45) Unpacking objects:  93% (42/45) Unpacking objects:  95% (43/45) Unpacking objects:  97% (44/45) Unpacking objects: 100% (45/45) Unpacking objects: 100% (45/45), done.
2020-04-23 13:31:17 | stdout | Unpacking objects:   2% (1/45) Unpacking objects:   4% (2/45) Unpacking objects:   6% (3/45) Unpacking objects:   8% (4/45) Unpacking objects:  11% (5/45) Unpacking objects:  13% (6/45) Unpacking objects:  15% (7/45) Unpacking objects:  17% (8/45) Unpacking objects:  20% (9/45) Unpacking objects:  22% (10/45) Unpacking objects:  24% (11/45) Unpacking objects:  26% (12/45) Unpacking objects:  28% (13/45) Unpacking objects:  31% (14/45) Unpacking objects:  33% (15/45) Unpacking objects:  35% (16/45) Unpacking objects:  37% (17/45) Unpacking objects:  40% (18/45) Unpacking objects:  42% (19/45) Unpacking objects:  44% (20/45) Unpacking objects:  46% (21/45) Unpacking objects:  48% (22/45) remote: Total 45 (delta 2), reused 24 (delta 0), pack-reused 0[K
2020-04-23 13:31:16 | stdout | remote: Compressing objects:   2% (1/41)[K remote: Compressing objects:   4% (2/41)[K remote: Compressing objects:   7% (3/41)[K remote: Compressing objects:   9% (4/41)[K remote: Compressing objects:  12% (5/41)[K remote: Compressing objects:  14% (6/41)[K remote: Compressing objects:  17% (7/41)[K remote: Compressing objects:  19% (8/41)[K remote: Compressing objects:  21% (9/41)[K remote: Compressing objects:  24% (10/41)[K remote: Compressing objects:  26% (11/41)[K remote: Compressing objects:  29% (12/41)[K remote: Compressing objects:  31% (13/41)[K remote: Compressing objects:  34% (14/41)[K remote: Compressing objects:  36% (15/41)[K remote: Compressing objects:  39% (16/41)[K remote: Compressing objects:  41% (17/41)[K remote: Compressing objects:  43% (18/41)[K remote: Compressing objects:  46% (19/41)[K remote: Compressing objects:  48% (20/41)[K remote: Compressing objects:  51% (21/41)[K remote: Compressing objects:  53% (22/41)[K remote: Compressing objects:  56% (23/41)[K remote: Compressing objects:  58% (24/41)[K remote: Compressing objects:  60% (25/41)[K remote: Compressing objects:  63% (26/41)[K remote: Compressing objects:  65% (27/41)[K remote: Compressing objects:  68% (28/41)[K remote: Compressing objects:  70% (29/41)[K remote: Compressing objects:  73% (30/41)[K remote: Compressing objects:  75% (31/41)[K remote: Compressing objects:  78% (32/41)[K remote: Compressing objects:  80% (33/41)[K remote: Compressing objects:  82% (34/41)[K remote: Compressing objects:  85% (35/41)[K remote: Compressing objects:  87% (36/41)[K remote: Compressing objects:  90% (37/41)[K remote: Compressing objects:  92% (38/41)[K remote: Compressing objects:  95% (39/41)[K remote: Compressing objects:  97% (40/41)[K remote: Compressing objects: 100% (41/41)[K remote: Compressing objects: 100% (41/41), done.[K
2020-04-23 13:31:16 | stdout | remote: Counting objects:   2% (1/45)[K remote: Counting objects:   4% (2/45)[K remote: Counting objects:   6% (3/45)[K remote: Counting objects:   8% (4/45)[K remote: Counting objects:  11% (5/45)[K remote: Counting objects:  13% (6/45)[K remote: Counting objects:  15% (7/45)[K remote: Counting objects:  17% (8/45)[K remote: Counting objects:  20% (9/45)[K remote: Counting objects:  22% (10/45)[K remote: Counting objects:  24% (11/45)[K remote: Counting objects:  26% (12/45)[K remote: Counting objects:  28% (13/45)[K remote: Counting objects:  31% (14/45)[K remote: Counting objects:  33% (15/45)[K remote: Counting objects:  35% (16/45)[K remote: Counting objects:  37% (17/45)[K remote: Counting objects:  40% (18/45)[K remote: Counting objects:  42% (19/45)[K remote: Counting objects:  44% (20/45)[K remote: Counting objects:  46% (21/45)[K remote: Counting objects:  48% (22/45)[K remote: Counting objects:  51% (23/45)[K remote: Counting objects:  53% (24/45)[K remote: Counting objects:  55% (25/45)[K remote: Counting objects:  57% (26/45)[K remote: Counting objects:  60% (27/45)[K remote: Counting objects:  62% (28/45)[K remote: Counting objects:  64% (29/45)[K remote: Counting objects:  66% (30/45)[K remote: Counting objects:  68% (31/45)[K remote: Counting objects:  71% (32/45)[K remote: Counting objects:  73% (33/45)[K remote: Counting objects:  75% (34/45)[K remote: Counting objects:  77% (35/45)[K remote: Counting objects:  80% (36/45)[K remote: Counting objects:  82% (37/45)[K remote: Counting objects:  84% (38/45)[K remote: Counting objects:  86% (39/45)[K remote: Counting objects:  88% (40/45)[K remote: Counting objects:  91% (41/45)[K remote: Counting objects:  93% (42/45)[K remote: Counting objects:  95% (43/45)[K remote: Counting objects:  97% (44/45)[K remote: Counting objects: 100% (45/45)[K remote: Counting objects: 100% (45/45), done.[K
2020-04-23 13:31:16 | stdout | remote: Enumerating objects: 45, done.[K
2020-04-23 13:31:16 | stdout | Cloning into '/var/www/ttrss/plugins.local/feediron'...
2020-04-23 13:31:16 | stdout | Unpacking objects:  12% (1/8) Unpacking objects:  25% (2/8) Unpacking objects:  37% (3/8) Unpacking objects:  50% (4/8) Unpacking objects:  62% (5/8) Unpacking objects:  75% (6/8) Unpacking objects:  87% (7/8) Unpacking objects: 100% (8/8) Unpacking objects: 100% (8/8), done.
2020-04-23 13:31:16 | stdout | remote: Total 8 (delta 0), reused 8 (delta 0), pack-reused 0[K
2020-04-23 13:31:16 | stdout | remote: Compressing objects:  12% (1/8)[K remote: Compressing objects:  25% (2/8)[K remote: Compressing objects:  37% (3/8)[K remote: Compressing objects:  50% (4/8)[K remote: Compressing objects:  62% (5/8)[K remote: Compressing objects:  75% (6/8)[K remote: Compressing objects:  87% (7/8)[K remote: Compressing objects: 100% (8/8)[K remote: Compressing objects: 100% (8/8), done.[K
2020-04-23 13:31:16 | stdout | remote: Counting objects:  12% (1/8)[K remote: Counting objects:  25% (2/8)[K remote: Counting objects:  37% (3/8)[K remote: Counting objects:  50% (4/8)[K remote: Counting objects:  62% (5/8)[K remote: Counting objects:  75% (6/8)[K remote: Counting objects:  87% (7/8)[K remote: Counting objects: 100% (8/8)[K remote: Counting objects: 100% (8/8), done.[K
2020-04-23 13:31:16 | stdout | remote: Enumerating objects: 8, done.[K
2020-04-23 13:31:15 | stdout | Cloning into '/var/www/ttrss/plugins.local/mobilize'...
2020-04-23 13:31:14 | stdout | Resolving deltas:   0% (0/439) Resolving deltas:   1% (5/439) Resolving deltas:   2% (9/439) Resolving deltas:   3% (15/439) Resolving deltas:   4% (19/439) Resolving deltas:   5% (22/439) Resolving deltas:   6% (28/439) Resolving deltas:   8% (37/439) Resolving deltas:  11% (50/439) Resolving deltas:  12% (53/439) Resolving deltas:  13% (59/439) Resolving deltas:  14% (65/439) Resolving deltas:  15% (66/439) Resolving deltas:  17% (75/439) Resolving deltas:  18% (80/439) Resolving deltas:  19% (84/439) Resolving deltas:  20% (88/439) Resolving deltas:  21% (93/439) Resolving deltas:  22% (97/439) Resolving deltas:  23% (102/439) Resolving deltas:  24% (106/439) Resolving deltas:  25% (110/439) Resolving deltas:  26% (115/439) Resolving deltas:  27% (120/439) Resolving deltas:  28% (123/439) Resolving deltas:  29% (128/439) Resolving deltas:  30% (132/439) Resolving deltas:  36% (159/439) Resolving deltas:  44% (194/439) Resolving deltas:  45% (198/439) Resolving deltas:  46% (204/439) Resolving deltas:  47% (210/439) Resolving deltas:  48% (211/439) Resolving deltas:  49% (216/439) Resolving deltas:  50% (220/439) Resolving deltas:  51% (226/439) Resolving deltas:  52% (229/439) Resolving deltas:  53% (234/439) Resolving deltas:  54% (238/439) Resolving deltas:  55% (242/439) Resolving deltas:  58% (258/439) Resolving deltas:  59% (260/439) Resolving deltas:  60% (265/439) Resolving deltas:  61% (271/439) Resolving deltas:  62% (275/439) Resolving deltas:  63% (277/439) Resolving deltas:  64% (281/439) Resolving deltas:  65% (286/439) Resolving deltas:  66% (292/439) Resolving deltas:  67% (295/439) Resolving deltas:  68% (299/439) Resolving deltas:  69% (303/439) Resolving deltas:  71% (312/439) Resolving deltas:  72% (319/439) Resolving deltas:  73% (321/439) Resolving deltas:  74% (325/439) Resolving deltas:  75% (330/439) Resolving deltas:  76% (334/439) Resolving deltas:  77% (339/439) Resolving deltas:  78% (343/439) Resolving deltas:  79% (347/439) Resolving deltas:  80% (352/439) Resolving deltas:  81% (356/439) Resolving deltas:  82% (360/439) Resolving deltas:  83% (365/439) Resolving deltas:  84% (369/439) Resolving deltas:  85% (374/439) Resolving deltas:  86% (378/439) Resolving deltas:  87% (382/439) Resolving deltas:  88% (387/439) Resolving deltas:  89% (391/439) Resolving deltas:  90% (396/439) Resolving deltas:  91% (401/439) Resolving deltas:  92% (404/439) Resolving deltas:  93% (410/439) Resolving deltas:  94% (413/439) Resolving deltas:  95% (418/439) Resolving deltas:  98% (432/439) Resolving deltas: 100% (439/439) Resolving deltas: 100% (439/439), done.
2020-04-23 13:31:14 | stdout | Receiving objects:  96% (2907/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  97% (2938/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  98% (2968/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  99% (2998/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects: 100% (3028/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects: 100% (3028/3028), 3.44 MiB \| 4.46 MiB/s, done.
2020-04-23 13:31:13 | stdout | Receiving objects:   0% (1/3028) Receiving objects:   1% (31/3028) Receiving objects:   2% (61/3028) Receiving objects:   3% (91/3028) Receiving objects:   4% (122/3028) Receiving objects:   5% (152/3028) Receiving objects:   6% (182/3028) Receiving objects:   7% (212/3028) Receiving objects:   8% (243/3028) Receiving objects:   9% (273/3028) Receiving objects:  10% (303/3028) Receiving objects:  11% (334/3028) Receiving objects:  12% (364/3028) Receiving objects:  13% (394/3028) Receiving objects:  14% (424/3028) Receiving objects:  15% (455/3028) Receiving objects:  16% (485/3028) Receiving objects:  17% (515/3028) Receiving objects:  18% (546/3028) Receiving objects:  19% (576/3028) Receiving objects:  20% (606/3028) Receiving objects:  21% (636/3028) Receiving objects:  22% (667/3028) Receiving objects:  23% (697/3028) Receiving objects:  24% (727/3028) Receiving objects:  25% (757/3028) Receiving objects:  26% (788/3028) Receiving objects:  27% (818/3028) Receiving objects:  28% (848/3028) Receiving objects:  29% (879/3028) Receiving objects:  30% (909/3028) Receiving objects:  31% (939/3028) Receiving objects:  32% (969/3028) Receiving objects:  33% (1000/3028) Receiving objects:  34% (1030/3028) Receiving objects:  35% (1060/3028) Receiving objects:  36% (1091/3028) Receiving objects:  37% (1121/3028) Receiving objects:  38% (1151/3028) Receiving objects:  39% (1181/3028) Receiving objects:  40% (1212/3028) Receiving objects:  41% (1242/3028) Receiving objects:  42% (1272/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  43% (1303/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  44% (1333/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  45% (1363/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  46% (1393/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  47% (1424/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  48% (1454/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  49% (1484/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  50% (1514/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  51% (1545/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  52% (1575/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  53% (1605/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  54% (1636/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  55% (1666/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  56% (1696/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  57% (1726/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  58% (1757/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  59% (1787/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  60% (1817/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  61% (1848/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  62% (1878/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  63% (1908/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  64% (1938/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  65% (1969/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  66% (1999/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  67% (2029/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  68% (2060/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  69% (2090/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  70% (2120/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  71% (2150/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  72% (2181/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  73% (2211/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  74% (2241/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  75% (2271/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  76% (2302/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  77% (2332/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  78% (2362/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  79% (2393/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  80% (2423/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  81% (2453/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  82% (2483/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  83% (2514/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  84% (2544/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  85% (2574/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  86% (2605/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  87% (2635/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  88% (2665/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  89% (2695/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  90% (2726/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  91% (2756/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  92% (2786/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  93% (2817/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  94% (2847/3028), 880.00 KiB \| 1.71 MiB/s Receiving objects:  95% (2877/3028), 880.00 KiB \| 1.71 MiB/s remote: Total 3028 (delta 439), reused 1855 (delta 230)
2020-04-23 13:31:12 | stdout | remote: Compressing objects:   0% (1/2675)[K remote: Compressing objects:   1% (27/2675)[K remote: Compressing objects:   2% (54/2675)[K remote: Compressing objects:   3% (81/2675)[K remote: Compressing objects:   4% (107/2675)[K remote: Compressing objects:   5% (134/2675)[K remote: Compressing objects:   6% (161/2675)[K remote: Compressing objects:   7% (188/2675)[K remote: Compressing objects:   8% (214/2675)[K remote: Compressing objects:   9% (241/2675)[K remote: Compressing objects:  10% (268/2675)[K remote: Compressing objects:  11% (295/2675)[K remote: Compressing objects:  12% (321/2675)[K remote: Compressing objects:  13% (348/2675)[K remote: Compressing objects:  14% (375/2675)[K remote: Compressing objects:  15% (402/2675)[K remote: Compressing objects:  16% (428/2675)[K remote: Compressing objects:  17% (455/2675)[K remote: Compressing objects:  18% (482/2675)[K remote: Compressing objects:  19% (509/2675)[K remote: Compressing objects:  20% (535/2675)[K remote: Compressing objects:  21% (562/2675)[K remote: Compressing objects:  22% (589/2675)[K remote: Compressing objects:  23% (616/2675)[K remote: Compressing objects:  24% (642/2675)[K remote: Compressing objects:  25% (669/2675)[K remote: Compressing objects:  26% (696/2675)[K remote: Compressing objects:  27% (723/2675)[K remote: Compressing objects:  28% (749/2675)[K remote: Compressing objects:  29% (776/2675)[K remote: Compressing objects:  30% (803/2675)[K remote: Compressing objects:  31% (830/2675)[K remote: Compressing objects:  32% (856/2675)[K remote: Compressing objects:  33% (883/2675)[K remote: Compressing objects:  34% (910/2675)[K remote: Compressing objects:  35% (937/2675)[K remote: Compressing objects:  36% (963/2675)[K remote: Compressing objects:  37% (990/2675)[K remote: Compressing objects:  38% (1017/2675)[K remote: Compressing objects:  39% (1044/2675)[K remote: Compressing objects:  40% (1070/2675)[K remote: Compressing objects:  41% (1097/2675)[K remote: Compressing objects:  42% (1124/2675)[K remote: Compressing objects:  43% (1151/2675)[K remote: Compressing objects:  44% (1177/2675)[K remote: Compressing objects:  45% (1204/2675)[K remote: Compressing objects:  46% (1231/2675)[K remote: Compressing objects:  47% (1258/2675)[K remote: Compressing objects:  48% (1284/2675)[K remote: Compressing objects:  49% (1311/2675)[K remote: Compressing objects:  50% (1338/2675)[K remote: Compressing objects:  51% (1365/2675)[K remote: Compressing objects:  52% (1391/2675)[K remote: Compressing objects:  53% (1418/2675)[K remote: Compressing objects:  54% (1445/2675)[K remote: Compressing objects:  55% (1472/2675)[K remote: Compressing objects:  56% (1498/2675)[K remote: Compressing objects:  57% (1525/2675)[K remote: Compressing objects:  58% (1552/2675)[K remote: Compressing objects:  59% (1579/2675)[K remote: Compressing objects:  60% (1605/2675)[K remote: Compressing objects:  61% (1632/2675)[K remote: Compressing objects:  62% (1659/2675)[K remote: Compressing objects:  63% (1686/2675)[K remote: Compressing objects:  64% (1712/2675)[K remote: Compressing objects:  65% (1739/2675)[K remote: Compressing objects:  66% (1766/2675)[K remote: Compressing objects:  67% (1793/2675)[K remote: Compressing objects:  68% (1819/2675)[K remote: Compressing objects:  69% (1846/2675)[K remote: Compressing objects:  70% (1873/2675)[K remote: Compressing objects:  71% (1900/2675)[K remote: Compressing objects:  72% (1926/2675)[K remote: Compressing objects:  73% (1953/2675)[K remote: Compressing objects:  74% (1980/2675)[K remote: Compressing objects:  75% (2007/2675)[K remote: Compressing objects:  76% (2033/2675)[K remote: Compressing objects:  77% (2060/2675)[K remote: Compressing objects:  78% (2087/2675)[K remote: Compressing objects:  79% (2114/2675)[K remote: Compressing objects:  80% (2140/2675)[K remote: Compressing objects:  81% (2167/2675)[K remote: Compressing objects:  82% (2194/2675)[K remote: Compressing objects:  83% (2221/2675)[K remote: Compressing objects:  84% (2247/2675)[K remote: Compressing objects:  85% (2274/2675)[K remote: Compressing objects:  86% (2301/2675)[K remote: Compressing objects:  87% (2328/2675)[K remote: Compressing objects:  88% (2354/2675)[K remote: Compressing objects:  89% (2381/2675)[K remote: Compressing objects:  90% (2408/2675)[K remote: Compressing objects:  91% (2435/2675)[K remote: Compressing objects:  92% (2461/2675)[K remote: Compressing objects:  93% (2488/2675)[K remote: Compressing objects:  94% (2515/2675)[K remote: Compressing objects:  95% (2542/2675)[K remote: Compressing objects:  96% (2568/2675)[K remote: Compressing objects:  97% (2595/2675)[K remote: Compressing objects:  98% (2622/2675)[K remote: Compressing objects:  99% (2649/2675)[K remote: Compressing objects: 100% (2675/2675)[K remote: Compressing objects: 100% (2675/2675), done.[K
2020-04-23 13:31:12 | stdout | remote: Counting objects:   0% (1/3028)[K remote: Counting objects:   1% (31/3028)[K remote: Counting objects:   2% (61/3028)[K remote: Counting objects:   3% (91/3028)[K remote: Counting objects:   4% (122/3028)[K remote: Counting objects:   5% (152/3028)[K remote: Counting objects:   6% (182/3028)[K remote: Counting objects:   7% (212/3028)[K remote: Counting objects:   8% (243/3028)[K remote: Counting objects:   9% (273/3028)[K remote: Counting objects:  10% (303/3028)[K remote: Counting objects:  11% (334/3028)[K remote: Counting objects:  12% (364/3028)[K remote: Counting objects:  13% (394/3028)[K remote: Counting objects:  14% (424/3028)[K remote: Counting objects:  15% (455/3028)[K remote: Counting objects:  16% (485/3028)[K remote: Counting objects:  17% (515/3028)[K remote: Counting objects:  18% (546/3028)[K remote: Counting objects:  19% (576/3028)[K remote: Counting objects:  20% (606/3028)[K remote: Counting objects:  21% (636/3028)[K remote: Counting objects:  22% (667/3028)[K remote: Counting objects:  23% (697/3028)[K remote: Counting objects:  24% (727/3028)[K remote: Counting objects:  25% (757/3028)[K remote: Counting objects:  26% (788/3028)[K remote: Counting objects:  27% (818/3028)[K remote: Counting objects:  28% (848/3028)[K remote: Counting objects:  29% (879/3028)[K remote: Counting objects:  30% (909/3028)[K remote: Counting objects:  31% (939/3028)[K remote: Counting objects:  32% (969/3028)[K remote: Counting objects:  33% (1000/3028)[K remote: Counting objects:  34% (1030/3028)[K remote: Counting objects:  35% (1060/3028)[K remote: Counting objects:  36% (1091/3028)[K remote: Counting objects:  37% (1121/3028)[K remote: Counting objects:  38% (1151/3028)[K remote: Counting objects:  39% (1181/3028)[K remote: Counting objects:  40% (1212/3028)[K remote: Counting objects:  41% (1242/3028)[K remote: Counting objects:  42% (1272/3028)[K remote: Counting objects:  43% (1303/3028)[K remote: Counting objects:  44% (1333/3028)[K remote: Counting objects:  45% (1363/3028)[K remote: Counting objects:  46% (1393/3028)[K remote: Counting objects:  47% (1424/3028)[K remote: Counting objects:  48% (1454/3028)[K remote: Counting objects:  49% (1484/3028)[K remote: Counting objects:  50% (1514/3028)[K remote: Counting objects:  51% (1545/3028)[K remote: Counting objects:  52% (1575/3028)[K remote: Counting objects:  53% (1605/3028)[K remote: Counting objects:  54% (1636/3028)[K remote: Counting objects:  55% (1666/3028)[K remote: Counting objects:  56% (1696/3028)[K remote: Counting objects:  57% (1726/3028)[K remote: Counting objects:  58% (1757/3028)[K remote: Counting objects:  59% (1787/3028)[K remote: Counting objects:  60% (1817/3028)[K remote: Counting objects:  61% (1848/3028)[K remote: Counting objects:  62% (1878/3028)[K remote: Counting objects:  63% (1908/3028)[K remote: Counting objects:  64% (1938/3028)[K remote: Counting objects:  65% (1969/3028)[K remote: Counting objects:  66% (1999/3028)[K remote: Counting objects:  67% (2029/3028)[K remote: Counting objects:  68% (2060/3028)[K remote: Counting objects:  69% (2090/3028)[K remote: Counting objects:  70% (2120/3028)[K remote: Counting objects:  71% (2150/3028)[K remote: Counting objects:  72% (2181/3028)[K remote: Counting objects:  73% (2211/3028)[K remote: Counting objects:  74% (2241/3028)[K remote: Counting objects:  75% (2271/3028)[K remote: Counting objects:  76% (2302/3028)[K remote: Counting objects:  77% (2332/3028)[K remote: Counting objects:  78% (2362/3028)[K remote: Counting objects:  79% (2393/3028)[K remote: Counting objects:  80% (2423/3028)[K remote: Counting objects:  81% (2453/3028)[K remote: Counting objects:  82% (2483/3028)[K remote: Counting objects:  83% (2514/3028)[K remote: Counting objects:  84% (2544/3028)[K remote: Counting objects:  85% (2574/3028)[K remote: Counting objects:  86% (2605/3028)[K remote: Counting objects:  87% (2635/3028)[K remote: Counting objects:  88% (2665/3028)[K remote: Counting objects:  89% (2695/3028)[K remote: Counting objects:  90% (2726/3028)[K remote: Counting objects:  91% (2756/3028)[K remote: Counting objects:  92% (2786/3028)[K remote: Counting objects:  93% (2817/3028)[K remote: Counting objects:  94% (2847/3028)[K remote: Counting objects:  95% (2877/3028)[K remote: Counting objects:  96% (2907/3028)[K remote: Counting objects:  97% (2938/3028)[K remote: Counting objects:  98% (2968/3028)[K remote: Counting objects:  99% (2998/3028)[K remote: Counting objects: 100% (3028/3028)[K remote: Counting objects: 100% (3028/3028), done.[K
2020-04-23 13:31:12 | stdout | remote: Enumerating objects: 3028, done.[K
2020-04-23 13:31:09 | stdout | Cloning into '/var/www/ttrss'...
2020-04-23 13:31:09 | stdout | Setup: Setting up Tiny Tiny RSS (latest revision) ...
2020-04-23 13:31:09 | stdout | Setup:                You have been warned.
2020-04-23 13:31:09 | stdout | Setup: !!! This is not recommended for a production server !!!
2020-04-23 13:31:09 | stdout | Setup: !!! WARNING - No encryption (TLS) used - WARNING    !!!
2020-04-23 13:31:09 | stdout | [cont-init.d] 99-ttrss: executing...
2020-04-23 13:31:08 | stdout | [cont-init.d] 98-wait-for-db: exited 0.
2020-04-23 13:31:08 | stdout | Checking database responds within 1s on 172.17.0.3:5432...
2020-04-23 13:31:08 | stdout | [cont-init.d] 98-wait-for-db: executing...
2020-04-23 13:31:08 | stdout | [cont-init.d] 50-php: exited 0.
2020-04-23 13:31:08 | stdout | rm: can't remove '/usr/sbin/php-fpm': No such file or directory
2020-04-23 13:31:08 | stdout | [cont-init.d] 50-php: executing...
2020-04-23 13:31:08 | stdout | [cont-init.d] executing container initialization scripts...
2020-04-23 13:31:08 | stdout | [fix-attrs.d] done.
2020-04-23 13:31:08 | stdout | [fix-attrs.d] applying ownership & permissions fixes...
2020-04-23 13:31:08 | stdout | [s6-init] ensuring user provided files have correct perms...exited 0.
2020-04-23 13:31:06 | stdout | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.

```

Visiting the URL gives me a "startup failed, set SELF_URL_PATH" message
![Screen Shot 2020-04-23 at 9 46 21 AM](https://user-images.githubusercontent.com/14184529/80106053-57c63080-8547-11ea-9867-c39bc5bd0b4d.png)

Does anybody have any insight into what's wrong with my configuration?

**Comment by bugwelle** [comment]
After recreating my ttrss container a few days ago, I get the same error message. The image wasn't updated in quite some time, though. I guess ttrss changed something in their GitHub repo and the docker image does not reflect it, yet?

Everything worked fine a week (or few weeks) ago. :-)

**Comment by nemosmithasf** [comment]
> Everything worked fine a week (or few weeks) ago. :-)
Is there a way to use an older version of TTRSS? I've tried 2-3 other docker images and they all have the same error for `SELF_URL_PATH` and some flavour of error in the logs

**Comment by samcre** [comment]
@nemosmithasf You can fix `SELF_URL_PATH` issue in the meantime with the workaround proposed in [this issue](https://github.com/x86dev/docker-ttrss/issues/39#issuecomment-616696107).

**Comment by eric-pierce** [comment]
I just created pull request #41 to resolve

**Comment by eric-pierce** [comment]
With pull request #41 merged this should be resolved.

**Comment by Ambroisie** [comment]
I also have the issue with "relation "ttrss_version" does not exist", with the latest docker image pulled.

**Comment by eric-pierce** [comment]
@Ambroisie re-starting your container should resolve this, the container hasn't finished initializing the database.

**Comment by m0nhawk** [comment]
It still happens with the latest Docker image for a clean install.

**Comment by x86dev** [comment]
PR #45 was merged -- please retry and let me know if the issue persists. Thanks!

**Comment by Ambroisie** [comment]
I am not going to be using this software after reading up on the author, but thank you for your work.

**Comment by AnsgarSchmidt** [comment]
Hi,
still having the same problem here.

```
/ # env
TTRSS_SELF_URL_PATH=https://ttrss.23-5.eu
HOSTNAME=e5426eaf0a8e
DB_PORT=5432
SHLVL=1
DB_ENV_PASS=ttrss
HOME=/root
DB_NAME=ttrss
DB_ENV_USER=ttrss
TERM=xterm
SELF_URL_PATH=https://ttrss.23-5.eu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TTRSS_DB_PORT_5432_TCP_ADDR=postgres
TTRSS_DB_HOST=postgres
TTRSS_DB_USER=ttrss
TTRSS_DB_PORT_5432_TCP_PORT=5432
TTRSS_DB_PSS=ttrss
DB_PASS=ttrss
TTRSS_DB_PORT=5432
TTRSS_DB_NAME=ttrss
PWD=/
DB_PORT_5432_TCP_ADDR=postgres
DB_HOST=postgres
DB_USER=ttrss
DB_PORT_5432_TCP_PORT=5432
```

I added 
TTRSS_SELF_URL_PATH=https://ttrss.23-5.eu
SELF_URL_PATH=https://ttrss.23-5.eu

but still getting 

Please set Config::get(Config::SELF_URL_PATH) to the correct value detected for your server: https://ttrss.23-5.eu/ (you're using: http://localhost/)

**Comment by AnsgarSchmidt** [comment]
Changing the /var/www/ttrss/config.php inside the container can be used as a quick-fix.
